CREATE DATABASE DB_CASA_DIAZ;

CREATE TABLE PRO_PRODUCTOS (
    "PRO_PRODUCTOS_ID" INT NOT NULL IDENTITY(1,1),
    "PRO_PRODUCTOS_CODIGO" INT NOT NULL,
    "PRO_PRODUCTOS_NOMBRE" VARCHAR(45) NOT NULL,
    "PRO_PRODUCTOS_STOCK" VARCHAR(45) NULL,
    "PRO_PRODUCTOS_MARCA" VARCHAR(25) NOT NULL,
    "PRO_PRODUCTOS_PRECIO" INT,
    "PRO_PRODUCTOS_PROVEEDOR" VARCHAR(35),
    PRIMARY KEY(PRO_PRODUCTOS_CODIGO)
)