CREATE TABLE CLI_CLIENTES(
	CLI_CLIENTES_ID INT NOT NULL IDENTITY(1,1),
	CLI_CLIENTES_RUT INT NOT NULL,
	CLI_CLIENTES_DV VARCHAR(1) NOT NULL,
	CLI_CLIENTES_NOMBRE VARCHAR(50) NOT NULL,
	CLI_CLIENTES_EMAIL VARCHAR(50) NOT NULL,
	PRIMARY KEY (CLI_CLIENTES_ID)
	
)

CREATE TABLE PRO_PROVEEDORES(
    PRO_PROVEEDORES_ID INT NOT NULL IDENTITY(1,1),
    PRO_PROVEEDORES_RUT INT NOT NULL,
    PRO_PROVEEDORES_DV VARCHAR(1) NOT NULL,
    PRO_PROVEEDORES_NOMBREFANTASIA VARCHAR(40) NOT NULL,
    PRO_PROVEEDORES_RAZONSOCIAL VARCHAR(40) NOT NULL,
    PRO_PROVEEDORES_GIRO VARCHAR(40) NOT NULL,
    PRO_PROVEEDORES_DIRECCION VARCHAR(60) NOT NULL,
    PRO_PROVEEDORES_CIUDAD VARCHAR(50) NOT NULL,
    PRO_PROVEEDORES_REGION VARCHAR(50) NOT NULL,
    PRO_PROVEEDORES_TELEFONO INT NULL,
    PRO_PROVEEDORES_MOVIL INT NULL,
    PRO_PROVEEDORES_EMAIL VARCHAR(60) NULL,
    PRO_PROVEEDORES_WEB VARCHAR(70) NULL,
    PRIMARY KEY(PRO_PROVEEDORES_ID)
)

CREATE TABLE PRO_PRODUCTOS (
    PRO_PRODUCTOS_ID INT NOT NULL IDENTITY(1,1),
    PRO_PROVEEDORES_ID INT NOT NULL,
    PRO_PRODUCTOS_CODIGOPROVEEDOR INT NOT NULL,
    PRO_PRODUCTOS_CODIGODEBARRA INT NOT NULL,
    PRO_PRODUCTOS_NOMBRE VARCHAR(45) NOT NULL,
    PRO_PRODUCTOS_STOCK INT NULL,
    PRO_PRODUCTOS_MARCA VARCHAR(25) NOT NULL,
    PRO_PRODUCTOS_PRECIOCOMPRA INT NOT NULL,
    PRO_PRODUCTOS_PRECIOVENTA INT NOT NULL,
    PRO_PRUDUCTOS_ULTIMAREPOSICION DATE,
    PRIMARY KEY(PRO_PRODUCTOS_ID),
    FOREIGN KEY(PRO_PROVEEDORES_ID) REFERENCES PRO_PROVEEDORES(PRO_PROVEEDORES_ID)
)
CREATE TABLE LISTA_PRODUCTOS(
	LISTA_PRODUCTOS_ID INT NOT NULL IDENTITY(1,1),
	LISTA_PRODUCTOS_PRODUCTOID INT NOT NULL,
	PRIMARY KEY(LISTA_PRODUCTOS_ID),
	FOREIGN KEY(LISTA_PRODUCTOS_PRODUCTOID) REFERENCES PRO_PRODUCTOS(PRO_PRODUCTOS_ID)
)
CREATE TABLE VE_VENTAS(
	VE_VENTAS_ID INT NOT NULL IDENTITY(1,1),
	VE_VENTAS_LISTAPRODUCTOS INT NOT NULL,
	VE_VENTAS_TOTALVENTA INT NOT NULL,
	VE_VENTAS_DESCUENTO INT NULL,
	VE_VENTAS_FECHA DATE,
    VE_VENTAS_IDCLIENTE INT,
	PRIMARY KEY(VE_VENTAS_ID),
	FOREIGN KEY(VE_VENTAS_LISTAPRODUCTOS) REFERENCES LISTA_PRODUCTOS(LISTA_PRODUCTOS_ID),
    FOREIGN KEY(VE_VENTAS_IDCLIENTE) REFERENCES CLI_CLIENTES(CLI_CLIENTES_ID)
)
