CREATE TABLE CLI_CLIENTES(
	CLI_CLIENTES_ID INT NOT NULL IDENTITY(1,1),
	CLI_CLIENTES_RUT INT NOT NULL,
	CLI_CLIENTES_DV VARCHAR(1) NOT NULL,
	CLI_CLIENTES_NOMBRE VARCHAR(50) NOT NULL,
	CLI_CLIENTES_EMAIL VARCHAR(50) NOT NULL,
	PRIMARY KEY (CLI_CLIENTES_ID)
	
)

CREATE TABLE PRO_PROVEEDORES(
    PRO_PROVEEDORES_ID INT NOT NULL IDENTITY(1,1),
    PRO_PROVEEDORES_RUT INT NOT NULL,
    PRO_PROVEEDORES_DV VARCHAR(1) NOT NULL,
    PRO_PROVEEDORES_NOMBREFANTASIA VARCHAR(40) NOT NULL,
    PRO_PROVEEDORES_RAZONSOCIAL VARCHAR(40) NOT NULL,
    PRO_PROVEEDORES_GIRO VARCHAR(40) NOT NULL,
    PRO_PROVEEDORES_DIRECCION VARCHAR(50) NOT NULL,
    PRO_PROVEEDORES_CIUDAD VARCHAR(20) NOT NULL,
    PRO_PROVEEDORES_REGION VARCHAR(30) NOT NULL,
    PRO_PROVEEDORES_TELEFONO INT NULL,
    PRO_PROVEEDORES_MOVIL INT NULL,
    PRO_PROVEEDORES_EMAIL VARCHAR(20) NULL,
    PRO_PROVEEDORES_WEB VARCHAR(40) NULL,
    PRIMARY KEY(PRO_PROVEEDORES_ID)
)

CREATE TABLE PRO_PRODUCTOS (
    PRO_PRODUCTOS_ID INT NOT NULL IDENTITY(1,1),
    PRO_PROVEEDORES_ID INT NOT NULL,
    PRO_PRODUCTOS_CODIGOPROVEEDOR VARCHAR(13) NOT NULL,
    PRO_PRODUCTOS_CODIGODEBARRA VARCHAR(13) NOT NULL,
    PRO_PRODUCTOS_NOMBRE VARCHAR(45) NOT NULL,
    PRO_PRODUCTOS_STOCK INT NULL,
    PRO_PRODUCTOS_MARCA VARCHAR(25) NOT NULL,
    PRO_PRODUCTOS_PRECIOCOMPRA INT NOT NULL,
    PRO_PRODUCTOS_PRECIOVENTA INT NOT NULL,
    PRO_PRUDUCTOS_ULTIMAREPOSICION DATE,
    PRIMARY KEY(PRO_PRODUCTOS_ID),
    FOREIGN KEY(PRO_PROVEEDORES_ID) REFERENCES PRO_PROVEEDORES(PRO_PROVEEDORES_ID)
)
CREATE TABLE VE_VENTAS(
	VE_VENTAS_ID INT NOT NULL IDENTITY(1,1),
	VE_VENTAS_TOTALVENTA INT NOT NULL,
	VE_VENTAS_DESCUENTO FLOAT NULL,
	VE_VENTAS_FECHA DATE NOT NULL,
    VE_VENTAS_IDCLIENTE INT NULL,
	PRIMARY KEY(VE_VENTAS_ID),
    FOREIGN KEY(VE_VENTAS_IDCLIENTE) REFERENCES CLI_CLIENTES(CLI_CLIENTES_ID)
)
CREATE TABLE VENTA_PRODUCTOS(
	VENTA_PRODUCTOS_ID INT NOT NULL IDENTITY(1,1),
	VENTA_PRODUCTOS_PRODUCTOID INT NOT NULL,
    VENTA_PRODUCTOS_VENTAID INT NOT NULL,
    VENTA_PRODUCTOS_CANTIDAD INT NOT NULL, 
	PRIMARY KEY(VENTA_PRODUCTOS_ID),
	FOREIGN KEY(VENTA_PRODUCTOS_PRODUCTOID) REFERENCES PRO_PRODUCTOS(PRO_PRODUCTOS_ID),
    FOREIGN KEY(VENTA_PRODUCTOS_VENTAID) REFERENCES VE_VENTAS(VE_VENTAS_ID)
)
